### ISSUE TITLE
Y tensioner

### ISSUE THREAD

**Issue by roastcuprepeat** [endorphin3d/endorphin#6]
Hi,

Looking to make a left Y tensioner matching the right,  Could you make one or release the step file so we can edit it?

**Comment by endorphin3d** [comment]
I'll try to find time to do this over the Thanksgiving holiday. By the way, the STEP file for this project is already in the repo.

**Comment by roastcuprepeat** [comment]
Oh right I missed that.. Made one from the STEP file. Thanks!

**Comment by jefedahmer** [comment]
> Oh right I missed that.. Made one from the STEP file. Thanks!

Are you willing to share the stl file?
